project_id = "etrnqdvlnmnkfkenhpsf"

[functions.delete-user]
verify_jwt = false

[functions.export-course]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false